// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

#ifndef PROTOBUF_INCLUDED_Message_2eproto
#define PROTOBUF_INCLUDED_Message_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_Message_2eproto 

namespace protobuf_Message_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_Message_2eproto
namespace Message {
namespace protobuf {
class Msg;
class MsgDefaultTypeInternal;
extern MsgDefaultTypeInternal _Msg_default_instance_;
}  // namespace protobuf
}  // namespace Message
namespace google {
namespace protobuf {
template<> ::Message::protobuf::Msg* Arena::CreateMaybeMessage<::Message::protobuf::Msg>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace Message {
namespace protobuf {

// ===================================================================

class Msg : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Message.protobuf.Msg) */ {
 public:
  Msg();
  virtual ~Msg();

  Msg(const Msg& from);

  inline Msg& operator=(const Msg& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Msg(Msg&& from) noexcept
    : Msg() {
    *this = ::std::move(from);
  }

  inline Msg& operator=(Msg&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Msg& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Msg* internal_default_instance() {
    return reinterpret_cast<const Msg*>(
               &_Msg_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(Msg* other);
  friend void swap(Msg& a, Msg& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Msg* New() const final {
    return CreateMaybeMessage<Msg>(NULL);
  }

  Msg* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Msg>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Msg& from);
  void MergeFrom(const Msg& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Msg* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string ip = 3;
  bool has_ip() const;
  void clear_ip();
  static const int kIpFieldNumber = 3;
  const ::std::string& ip() const;
  void set_ip(const ::std::string& value);
  #if LANG_CXX11
  void set_ip(::std::string&& value);
  #endif
  void set_ip(const char* value);
  void set_ip(const char* value, size_t size);
  ::std::string* mutable_ip();
  ::std::string* release_ip();
  void set_allocated_ip(::std::string* ip);

  // optional string port = 4;
  bool has_port() const;
  void clear_port();
  static const int kPortFieldNumber = 4;
  const ::std::string& port() const;
  void set_port(const ::std::string& value);
  #if LANG_CXX11
  void set_port(::std::string&& value);
  #endif
  void set_port(const char* value);
  void set_port(const char* value, size_t size);
  ::std::string* mutable_port();
  ::std::string* release_port();
  void set_allocated_port(::std::string* port);

  // optional string operation = 11;
  bool has_operation() const;
  void clear_operation();
  static const int kOperationFieldNumber = 11;
  const ::std::string& operation() const;
  void set_operation(const ::std::string& value);
  #if LANG_CXX11
  void set_operation(::std::string&& value);
  #endif
  void set_operation(const char* value);
  void set_operation(const char* value, size_t size);
  ::std::string* mutable_operation();
  ::std::string* release_operation();
  void set_allocated_operation(::std::string* operation);

  // required int32 role = 1;
  bool has_role() const;
  void clear_role();
  static const int kRoleFieldNumber = 1;
  ::google::protobuf::int32 role() const;
  void set_role(::google::protobuf::int32 value);

  // required int32 msgCategory = 2;
  bool has_msgcategory() const;
  void clear_msgcategory();
  static const int kMsgCategoryFieldNumber = 2;
  ::google::protobuf::int32 msgcategory() const;
  void set_msgcategory(::google::protobuf::int32 value);

  // optional int32 int32op1 = 5;
  bool has_int32op1() const;
  void clear_int32op1();
  static const int kInt32Op1FieldNumber = 5;
  ::google::protobuf::int32 int32op1() const;
  void set_int32op1(::google::protobuf::int32 value);

  // optional int32 int32op2 = 6;
  bool has_int32op2() const;
  void clear_int32op2();
  static const int kInt32Op2FieldNumber = 6;
  ::google::protobuf::int32 int32op2() const;
  void set_int32op2(::google::protobuf::int32 value);

  // optional int64 int64op1 = 7;
  bool has_int64op1() const;
  void clear_int64op1();
  static const int kInt64Op1FieldNumber = 7;
  ::google::protobuf::int64 int64op1() const;
  void set_int64op1(::google::protobuf::int64 value);

  // optional int64 int64op2 = 8;
  bool has_int64op2() const;
  void clear_int64op2();
  static const int kInt64Op2FieldNumber = 8;
  ::google::protobuf::int64 int64op2() const;
  void set_int64op2(::google::protobuf::int64 value);

  // optional double dbop1 = 9;
  bool has_dbop1() const;
  void clear_dbop1();
  static const int kDbop1FieldNumber = 9;
  double dbop1() const;
  void set_dbop1(double value);

  // optional double dbop2 = 10;
  bool has_dbop2() const;
  void clear_dbop2();
  static const int kDbop2FieldNumber = 10;
  double dbop2() const;
  void set_dbop2(double value);

  // optional int64 int64result = 13;
  bool has_int64result() const;
  void clear_int64result();
  static const int kInt64ResultFieldNumber = 13;
  ::google::protobuf::int64 int64result() const;
  void set_int64result(::google::protobuf::int64 value);

  // optional double dbresult = 14;
  bool has_dbresult() const;
  void clear_dbresult();
  static const int kDbresultFieldNumber = 14;
  double dbresult() const;
  void set_dbresult(double value);

  // optional int32 int32result = 12;
  bool has_int32result() const;
  void clear_int32result();
  static const int kInt32ResultFieldNumber = 12;
  ::google::protobuf::int32 int32result() const;
  void set_int32result(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:Message.protobuf.Msg)
 private:
  void set_has_role();
  void clear_has_role();
  void set_has_msgcategory();
  void clear_has_msgcategory();
  void set_has_ip();
  void clear_has_ip();
  void set_has_port();
  void clear_has_port();
  void set_has_int32op1();
  void clear_has_int32op1();
  void set_has_int32op2();
  void clear_has_int32op2();
  void set_has_int64op1();
  void clear_has_int64op1();
  void set_has_int64op2();
  void clear_has_int64op2();
  void set_has_dbop1();
  void clear_has_dbop1();
  void set_has_dbop2();
  void clear_has_dbop2();
  void set_has_operation();
  void clear_has_operation();
  void set_has_int32result();
  void clear_has_int32result();
  void set_has_int64result();
  void clear_has_int64result();
  void set_has_dbresult();
  void clear_has_dbresult();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr ip_;
  ::google::protobuf::internal::ArenaStringPtr port_;
  ::google::protobuf::internal::ArenaStringPtr operation_;
  ::google::protobuf::int32 role_;
  ::google::protobuf::int32 msgcategory_;
  ::google::protobuf::int32 int32op1_;
  ::google::protobuf::int32 int32op2_;
  ::google::protobuf::int64 int64op1_;
  ::google::protobuf::int64 int64op2_;
  double dbop1_;
  double dbop2_;
  ::google::protobuf::int64 int64result_;
  double dbresult_;
  ::google::protobuf::int32 int32result_;
  friend struct ::protobuf_Message_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Msg

// required int32 role = 1;
inline bool Msg::has_role() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Msg::set_has_role() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Msg::clear_has_role() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Msg::clear_role() {
  role_ = 0;
  clear_has_role();
}
inline ::google::protobuf::int32 Msg::role() const {
  // @@protoc_insertion_point(field_get:Message.protobuf.Msg.role)
  return role_;
}
inline void Msg::set_role(::google::protobuf::int32 value) {
  set_has_role();
  role_ = value;
  // @@protoc_insertion_point(field_set:Message.protobuf.Msg.role)
}

// required int32 msgCategory = 2;
inline bool Msg::has_msgcategory() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Msg::set_has_msgcategory() {
  _has_bits_[0] |= 0x00000010u;
}
inline void Msg::clear_has_msgcategory() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void Msg::clear_msgcategory() {
  msgcategory_ = 0;
  clear_has_msgcategory();
}
inline ::google::protobuf::int32 Msg::msgcategory() const {
  // @@protoc_insertion_point(field_get:Message.protobuf.Msg.msgCategory)
  return msgcategory_;
}
inline void Msg::set_msgcategory(::google::protobuf::int32 value) {
  set_has_msgcategory();
  msgcategory_ = value;
  // @@protoc_insertion_point(field_set:Message.protobuf.Msg.msgCategory)
}

// optional string ip = 3;
inline bool Msg::has_ip() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Msg::set_has_ip() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Msg::clear_has_ip() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Msg::clear_ip() {
  ip_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_ip();
}
inline const ::std::string& Msg::ip() const {
  // @@protoc_insertion_point(field_get:Message.protobuf.Msg.ip)
  return ip_.GetNoArena();
}
inline void Msg::set_ip(const ::std::string& value) {
  set_has_ip();
  ip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Message.protobuf.Msg.ip)
}
#if LANG_CXX11
inline void Msg::set_ip(::std::string&& value) {
  set_has_ip();
  ip_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Message.protobuf.Msg.ip)
}
#endif
inline void Msg::set_ip(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_ip();
  ip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Message.protobuf.Msg.ip)
}
inline void Msg::set_ip(const char* value, size_t size) {
  set_has_ip();
  ip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Message.protobuf.Msg.ip)
}
inline ::std::string* Msg::mutable_ip() {
  set_has_ip();
  // @@protoc_insertion_point(field_mutable:Message.protobuf.Msg.ip)
  return ip_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Msg::release_ip() {
  // @@protoc_insertion_point(field_release:Message.protobuf.Msg.ip)
  if (!has_ip()) {
    return NULL;
  }
  clear_has_ip();
  return ip_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Msg::set_allocated_ip(::std::string* ip) {
  if (ip != NULL) {
    set_has_ip();
  } else {
    clear_has_ip();
  }
  ip_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ip);
  // @@protoc_insertion_point(field_set_allocated:Message.protobuf.Msg.ip)
}

// optional string port = 4;
inline bool Msg::has_port() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Msg::set_has_port() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Msg::clear_has_port() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Msg::clear_port() {
  port_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_port();
}
inline const ::std::string& Msg::port() const {
  // @@protoc_insertion_point(field_get:Message.protobuf.Msg.port)
  return port_.GetNoArena();
}
inline void Msg::set_port(const ::std::string& value) {
  set_has_port();
  port_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Message.protobuf.Msg.port)
}
#if LANG_CXX11
inline void Msg::set_port(::std::string&& value) {
  set_has_port();
  port_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Message.protobuf.Msg.port)
}
#endif
inline void Msg::set_port(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_port();
  port_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Message.protobuf.Msg.port)
}
inline void Msg::set_port(const char* value, size_t size) {
  set_has_port();
  port_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Message.protobuf.Msg.port)
}
inline ::std::string* Msg::mutable_port() {
  set_has_port();
  // @@protoc_insertion_point(field_mutable:Message.protobuf.Msg.port)
  return port_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Msg::release_port() {
  // @@protoc_insertion_point(field_release:Message.protobuf.Msg.port)
  if (!has_port()) {
    return NULL;
  }
  clear_has_port();
  return port_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Msg::set_allocated_port(::std::string* port) {
  if (port != NULL) {
    set_has_port();
  } else {
    clear_has_port();
  }
  port_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), port);
  // @@protoc_insertion_point(field_set_allocated:Message.protobuf.Msg.port)
}

// optional int32 int32op1 = 5;
inline bool Msg::has_int32op1() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void Msg::set_has_int32op1() {
  _has_bits_[0] |= 0x00000020u;
}
inline void Msg::clear_has_int32op1() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void Msg::clear_int32op1() {
  int32op1_ = 0;
  clear_has_int32op1();
}
inline ::google::protobuf::int32 Msg::int32op1() const {
  // @@protoc_insertion_point(field_get:Message.protobuf.Msg.int32op1)
  return int32op1_;
}
inline void Msg::set_int32op1(::google::protobuf::int32 value) {
  set_has_int32op1();
  int32op1_ = value;
  // @@protoc_insertion_point(field_set:Message.protobuf.Msg.int32op1)
}

// optional int32 int32op2 = 6;
inline bool Msg::has_int32op2() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void Msg::set_has_int32op2() {
  _has_bits_[0] |= 0x00000040u;
}
inline void Msg::clear_has_int32op2() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void Msg::clear_int32op2() {
  int32op2_ = 0;
  clear_has_int32op2();
}
inline ::google::protobuf::int32 Msg::int32op2() const {
  // @@protoc_insertion_point(field_get:Message.protobuf.Msg.int32op2)
  return int32op2_;
}
inline void Msg::set_int32op2(::google::protobuf::int32 value) {
  set_has_int32op2();
  int32op2_ = value;
  // @@protoc_insertion_point(field_set:Message.protobuf.Msg.int32op2)
}

// optional int64 int64op1 = 7;
inline bool Msg::has_int64op1() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void Msg::set_has_int64op1() {
  _has_bits_[0] |= 0x00000080u;
}
inline void Msg::clear_has_int64op1() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void Msg::clear_int64op1() {
  int64op1_ = GOOGLE_LONGLONG(0);
  clear_has_int64op1();
}
inline ::google::protobuf::int64 Msg::int64op1() const {
  // @@protoc_insertion_point(field_get:Message.protobuf.Msg.int64op1)
  return int64op1_;
}
inline void Msg::set_int64op1(::google::protobuf::int64 value) {
  set_has_int64op1();
  int64op1_ = value;
  // @@protoc_insertion_point(field_set:Message.protobuf.Msg.int64op1)
}

// optional int64 int64op2 = 8;
inline bool Msg::has_int64op2() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void Msg::set_has_int64op2() {
  _has_bits_[0] |= 0x00000100u;
}
inline void Msg::clear_has_int64op2() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void Msg::clear_int64op2() {
  int64op2_ = GOOGLE_LONGLONG(0);
  clear_has_int64op2();
}
inline ::google::protobuf::int64 Msg::int64op2() const {
  // @@protoc_insertion_point(field_get:Message.protobuf.Msg.int64op2)
  return int64op2_;
}
inline void Msg::set_int64op2(::google::protobuf::int64 value) {
  set_has_int64op2();
  int64op2_ = value;
  // @@protoc_insertion_point(field_set:Message.protobuf.Msg.int64op2)
}

// optional double dbop1 = 9;
inline bool Msg::has_dbop1() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void Msg::set_has_dbop1() {
  _has_bits_[0] |= 0x00000200u;
}
inline void Msg::clear_has_dbop1() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void Msg::clear_dbop1() {
  dbop1_ = 0;
  clear_has_dbop1();
}
inline double Msg::dbop1() const {
  // @@protoc_insertion_point(field_get:Message.protobuf.Msg.dbop1)
  return dbop1_;
}
inline void Msg::set_dbop1(double value) {
  set_has_dbop1();
  dbop1_ = value;
  // @@protoc_insertion_point(field_set:Message.protobuf.Msg.dbop1)
}

// optional double dbop2 = 10;
inline bool Msg::has_dbop2() const {
  return (_has_bits_[0] & 0x00000400u) != 0;
}
inline void Msg::set_has_dbop2() {
  _has_bits_[0] |= 0x00000400u;
}
inline void Msg::clear_has_dbop2() {
  _has_bits_[0] &= ~0x00000400u;
}
inline void Msg::clear_dbop2() {
  dbop2_ = 0;
  clear_has_dbop2();
}
inline double Msg::dbop2() const {
  // @@protoc_insertion_point(field_get:Message.protobuf.Msg.dbop2)
  return dbop2_;
}
inline void Msg::set_dbop2(double value) {
  set_has_dbop2();
  dbop2_ = value;
  // @@protoc_insertion_point(field_set:Message.protobuf.Msg.dbop2)
}

// optional string operation = 11;
inline bool Msg::has_operation() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Msg::set_has_operation() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Msg::clear_has_operation() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Msg::clear_operation() {
  operation_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_operation();
}
inline const ::std::string& Msg::operation() const {
  // @@protoc_insertion_point(field_get:Message.protobuf.Msg.operation)
  return operation_.GetNoArena();
}
inline void Msg::set_operation(const ::std::string& value) {
  set_has_operation();
  operation_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Message.protobuf.Msg.operation)
}
#if LANG_CXX11
inline void Msg::set_operation(::std::string&& value) {
  set_has_operation();
  operation_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Message.protobuf.Msg.operation)
}
#endif
inline void Msg::set_operation(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_operation();
  operation_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Message.protobuf.Msg.operation)
}
inline void Msg::set_operation(const char* value, size_t size) {
  set_has_operation();
  operation_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Message.protobuf.Msg.operation)
}
inline ::std::string* Msg::mutable_operation() {
  set_has_operation();
  // @@protoc_insertion_point(field_mutable:Message.protobuf.Msg.operation)
  return operation_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Msg::release_operation() {
  // @@protoc_insertion_point(field_release:Message.protobuf.Msg.operation)
  if (!has_operation()) {
    return NULL;
  }
  clear_has_operation();
  return operation_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Msg::set_allocated_operation(::std::string* operation) {
  if (operation != NULL) {
    set_has_operation();
  } else {
    clear_has_operation();
  }
  operation_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), operation);
  // @@protoc_insertion_point(field_set_allocated:Message.protobuf.Msg.operation)
}

// optional int32 int32result = 12;
inline bool Msg::has_int32result() const {
  return (_has_bits_[0] & 0x00002000u) != 0;
}
inline void Msg::set_has_int32result() {
  _has_bits_[0] |= 0x00002000u;
}
inline void Msg::clear_has_int32result() {
  _has_bits_[0] &= ~0x00002000u;
}
inline void Msg::clear_int32result() {
  int32result_ = 0;
  clear_has_int32result();
}
inline ::google::protobuf::int32 Msg::int32result() const {
  // @@protoc_insertion_point(field_get:Message.protobuf.Msg.int32result)
  return int32result_;
}
inline void Msg::set_int32result(::google::protobuf::int32 value) {
  set_has_int32result();
  int32result_ = value;
  // @@protoc_insertion_point(field_set:Message.protobuf.Msg.int32result)
}

// optional int64 int64result = 13;
inline bool Msg::has_int64result() const {
  return (_has_bits_[0] & 0x00000800u) != 0;
}
inline void Msg::set_has_int64result() {
  _has_bits_[0] |= 0x00000800u;
}
inline void Msg::clear_has_int64result() {
  _has_bits_[0] &= ~0x00000800u;
}
inline void Msg::clear_int64result() {
  int64result_ = GOOGLE_LONGLONG(0);
  clear_has_int64result();
}
inline ::google::protobuf::int64 Msg::int64result() const {
  // @@protoc_insertion_point(field_get:Message.protobuf.Msg.int64result)
  return int64result_;
}
inline void Msg::set_int64result(::google::protobuf::int64 value) {
  set_has_int64result();
  int64result_ = value;
  // @@protoc_insertion_point(field_set:Message.protobuf.Msg.int64result)
}

// optional double dbresult = 14;
inline bool Msg::has_dbresult() const {
  return (_has_bits_[0] & 0x00001000u) != 0;
}
inline void Msg::set_has_dbresult() {
  _has_bits_[0] |= 0x00001000u;
}
inline void Msg::clear_has_dbresult() {
  _has_bits_[0] &= ~0x00001000u;
}
inline void Msg::clear_dbresult() {
  dbresult_ = 0;
  clear_has_dbresult();
}
inline double Msg::dbresult() const {
  // @@protoc_insertion_point(field_get:Message.protobuf.Msg.dbresult)
  return dbresult_;
}
inline void Msg::set_dbresult(double value) {
  set_has_dbresult();
  dbresult_ = value;
  // @@protoc_insertion_point(field_set:Message.protobuf.Msg.dbresult)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf
}  // namespace Message

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_Message_2eproto
